pipeline {
    agent any
        stages {
            stage('One') {
                steps {
                        echo 'Hi, this is Nagesh from UVL'
                    }
            }
            stage('Two') {
                steps {
                        input('Do you want to procced?')
                    }
            }
            stage('Three') {
                    when {
                            not {
                                    branch "master"
                                }
                        }
                        steps {
                                echo "Hello"
                        }
            }
                                         

